### ISSUE TITLE
Errors with autogen.sh

### ISSUE THREAD

**Issue by mathomp4** [PRUNERS/ReMPI#2]
When I tried to run autogen.sh:

```
(1493)(master) $ ./autogen.sh
Running libtoolize --automake --copy ... 
Running autoreconf --verbose --install
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy
autoreconf: running: /discover/swdev/mathomp4/bin/autoconf
autoreconf: running: /discover/swdev/mathomp4/bin/autoheader
autoreconf: running: automake --add-missing --copy --no-force
configure.ac:13: warning: AM_INIT_AUTOMAKE: two- and three-arguments forms are deprecated.  For more info, see:
configure.ac:13: http://www.gnu.org/software/automake/manual/automake.html#Modernize-AM_005fINIT_005fAUTOMAKE-invocation
Makefile.am: error: required file './NEWS' not found
Makefile.am: error: required file './README' not found
Makefile.am: error: required file './AUTHORS' not found
Makefile.am: error: required file './ChangeLog' not found
autoreconf: automake failed with exit status: 1
Cleaning up ...
Now run ./configure.
```

I "solved" it by `touch`ing NEWS, README, AUTHORS, and ChangeLog, but I'm sure there's a more correct autotools way of doing that.

**Comment by dongahn** [comment]
@mathomp4: sorry I just saw this note. We will fix this issue with autotool way. 

Also, feel free to let us know your experiences of using ReMPI at NASA. IMHO, early experiences are extremely important to get right! From our early experiences here at LLNL so far, it was important to combine ReMPI with application-level non-determinism control. E.g., if you have dynamic load balancing which makes your MPI application sender non-determinism we may have to turn that off etc.

**Comment by kento** [comment]
I merged. Thanks you !
